# configuration.yaml
# Loads default set of integrations. Do not remove.
default_config:

# The Gateway communicates with Home Assistant via MQTT
mqtt:
  switch:
    - name: "Heatpump On"
      command_topic: "Heatpump/Command/HeatPumpEnabled"
      payload_on: "True"
      payload_off: "False"
      state_on: "On"
      state_off: "Off"
      unique_id: hewalex_heatpump_on_switch
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Hewalex Heatpump"
    - name: "Heatpump Deactivation"
      command_topic: "Heatpump/Command/ExtControllerHPOFF"
      payload_on: "True"
      payload_off: "False"
      state_on: "On"
      state_off: "Off"
      unique_id: hewalex_heatpump_extcontrol_switch
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Hewalex Heatpump"
  number:
    - name: "Hewalex Heatpump Set Hysteresis"
      command_topic: "Heatpump/Command/TapWaterHysteresis"
      state_topic: "Heatpump/TapWaterHysteresis"
      unit_of_measurement: "°C"
      max: 10
      unique_id: "hewalex_heatpump_hysteresis_set"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex Heatpump Set Tapwater Temp"
      command_topic: "Heatpump/Command/TapWaterTemp"
      state_topic: "Heatpump/TapWaterTemp"
      unit_of_measurement: "°C"
      max: 60
      min: 40
      unique_id: "hewalex_heatpump_tapwater_set"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
  sensor:
    - name: "Hewalex T1 Ambient Temp"
      state_topic: "Heatpump/T1"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t1"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Hewalex Heatpump"
    - name: "Hewalex T2 Bottom Tank Temp"
      state_topic: "Heatpump/T2"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t2"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex T3 Top Tank Temp"
      state_topic: "Heatpump/T3"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t3"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex T6 HP Water Inlet Temp"
      state_topic: "Heatpump/T6"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t6"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex T7 HP Water Outlet Temp)"
      state_topic: "Heatpump/T7"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t7"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex T8 HP Evaporator Temp"
      state_topic: "Heatpump/T8"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t8"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex T9 HP Pre Compressor Temp)"
      state_topic: "Heatpump/T9"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t9"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex T10 HP Post Compressor Temp)"
      state_topic: "Heatpump/T10"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_t10"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex HP Temp Setting"
      state_topic: "Heatpump/TapWaterTemp"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_tapwater"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex HP Status"
      state_topic: "Heatpump/HeatPumpEnabled"
      unique_id: "hewalex_heatpump_status"
      value_template: >-
        {% if value == "True" %}
            On
        {% else %}
            Off
        {% endif %}
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex HP Hysteresis"
      state_topic: "Heatpump/TapWaterHysteresis"
      unit_of_measurement: "°C"
      unique_id: "hewalex_heatpump_hysteresis"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex HP Circulation Pump"
      state_topic: "Heatpump/CirculationPumpON"
      unique_id: "hewalex_heatpump_waterpump"
      value_template: >-
        {% if value == "True" %}
            On
        {% else %}
            Off
        {% endif %}
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex HP Fan"
      state_topic: "Heatpump/FanON"
      unique_id: "hewalex_heatpump_fan"
      value_template: >-
        {% if value == "True" %}
            On
        {% else %}
            Off
        {% endif %}
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"
    - name: "Hewalex HP Expansion Valve"
      state_topic: "Heatpump/EV1"
      unit_of_measurement: "-/-"
      unique_id: "hewalex_heatpump_ev1"
      device:
        identifiers:
          - "hewalex_heatpump"
        name: "Heatpump Hewalex"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

powercalc:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
  - sensor:
      - name: "Import Laagtarief Sinds Begin Contract"
        state: "{{ (states('sensor.dsmr_reading_electricity_delivered_1') | float - 4675) | round(0) }}"

      - name: "Import Hoogtarief Sinds Begin Contract"
        state: "{{ (states('sensor.dsmr_reading_electricity_delivered_2') | float - 5171) | round(0) }}"

      - name: "Export Laagtarief Sinds Begin Contract"
        state: "{{ (states('sensor.dsmr_reading_electricity_returned_1') | float - 2588) | round(0) }}"

      - name: "Export Hoogtarief Sinds Begin Contract"
        state: "{{ (states('sensor.dsmr_reading_electricity_returned_2') | float - 5820) | round(0) }}"

      - name: "Saldo Laagtarief Sinds Begin Contract"
        state: "{{ (states('sensor.import_laagtarief_sinds_begin_contract') | float) - (states('sensor.export_laagtarief_sinds_begin_contract') | float) | round(0) }}"

      - name: "Saldo Hoogtarief Sinds Begin Contract"
        state: "{{ (states('sensor.import_hoogtarief_sinds_begin_contract') | float) - (states('sensor.export_hoogtarief_sinds_begin_contract') | float) | round(0) }}"
